keys:
  - &agenix-primary age154u8ykjvq5ey7jzt942ewa02ak4g0zygtzpv7jav9u2d48trq32svpc8jz

creation_rules:
  - path_regex: ^secrets/tailscale/secrets\.yaml$
    key_groups:
      - age:
          - *agenix-primary
