keys:
  - &desktop age1g8xl3ku8yaqypg94yhgh7fmspf4yn9d6fn3dp2vmkkfxpg9v3clqc3k6qf
  - &staging-vm age1v9tm9nunv6gsvf4kkj5emm8nw5elnh7z79hsa9fzd6j9v52zy46slj0e0g

creation_rules:
  - path_regex: ^secrets/tailscale/secrets\.yaml$
    key_groups:
      - age:
          - *desktop
          - *staging-vm
  - path_regex: ^secrets/terranix/cloudflare\.yaml$
    key_groups:
      - age:
          - *desktop
  - path_regex: ^secrets/(.*/)?staging-vm[.]yaml$
    key_groups:
      - age:
          - *desktop
          - *staging-vm
