keys:
  - &sam age1g8xl3ku8yaqypg94yhgh7fmspf4yn9d6fn3dp2vmkkfxpg9v3clqc3k6qf
  - &sam-personal-mac age19d25uasev50j02yjt574dt5t7ehzvftz0xsk4l4393vk7wh9udasxfkcrm
  - &staging-vm age1v9tm9nunv6gsvf4kkj5emm8nw5elnh7z79hsa9fzd6j9v52zy46slj0e0g
  - &teeny age16egjqzlqfukmyxgp3a60cr0xnheg9cw3gwzl5569hh2szyxhw5ksae60ug

creation_rules:
  - path_regex: ^secrets/development/secrets\.yaml$
    key_groups:
      - age:
          - *sam
          - *sam-personal-mac
          - *staging-vm
  - path_regex: ^secrets/media/secrets\.yaml$
    key_groups:
      - age:
          - *sam
          - *staging-vm
          - *teeny
  - path_regex: ^secrets/tailscale/secrets\.yaml$
    key_groups:
      - age:
          - *sam
          - *sam-personal-mac
          - *staging-vm
          - *teeny
  - path_regex: ^secrets/terranix/cloudflare\.yaml$
    key_groups:
      - age:
          - *sam
          - *sam-personal-mac
  - path_regex: ^secrets/(.*/)?staging-vm[.]yaml$
    key_groups:
      - age:
          - *sam
          - *staging-vm
  - path_regex: ^secrets/(.*/)?teeny[.]yaml$
    key_groups:
      - age:
          - *sam
          - *teeny
